# Uncomment the next line to define a global platform for your project
platform :ios, '11.0'

target 'slidingPeoplesCards' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for slidingPeoplesCards

  target 'slidingPeoplesCardsTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'slidingPeoplesCardsUITests' do
    # Pods for testing
  end

pod 'CardSlider'
end
